spring.application.name=ECommerceApi
jwt.secret = "WeNgPEXh0offvdxFTxX3ARnDO29EwBD8au63SUK6t1rhh4r8xNxqOAoYoWbfgJo7"
server.servlet.context-path=/api
stripe.secret.key= "sk_test_51T83vj1QMPuBMsiAK72jCGeLHUrD2gIdNd7C0vhaOP1SWueEXs5gKakK8vFkUlrHSECJaNP6DSDpAdIHecQUUOzX00tr6NQZGO"

spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce_api
spring.datasource.username=postgres
spring.datasource.password=191020
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
